USE MASTER IF EXISTS(SELECT * FROM SYS.databases WHERE NAME = 'Jardimdaeducacao')
DROP DATABASE Jardimdaeducacao
GO

CREATE DATABASE Jardimdaeducacao
GO

USE Jardimdaeducacao
GO

CREATE TABLE ALUNO(
ID_ALUNO INT PRIMARY KEY IDENTITY(1,1),--AUTONUMERICO
NOME_ALUNO VARCHAR (100),
DT_NASC_ALUNO DATE,
USER_ALUNO VARCHAR (15),
SENHA_ALUNO VARCHAR (15))
GO

INSERT INTO ALUNO VALUES
('SARAH GOMES', 
'01/03/2006',
'SGOMES',
'987654')

SELECT * FROM ALUNO
